### ISSUE TITLE
Ultimate Psionics - Fear Monger Archetype

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-Pathfinder#57]
Hi i made an ultimate psionics dread char with the fear monger archetype listed for it and well at lv1 i have 29 dc for my powers. It seems to be counting the total wisdom score instead of just the mod for the dc value. Is there a simple fix of changing something in the editor that i could do or just wait for the pack to be updated?.

thanks

From Email.

**Comment by psych777** [comment]
cannot figure this one out. not seeing any incorrect settings in the archetype. when looking at the fields on one of the powers the sDCBase is 10, the sDC (Final Spell DC) is 22 (currently have Wis set at 12 on the char) but the sDCAttr (Spell DC from Attr) is still set at 0. there is also an sOverclock (Overclock DC) that seems to always be set at 16, not sure what that is or where it gets its value. 
could it be that the Override Psionics Attribute being changed to Wisdom is adding the whole wisdom score instead of just using the modifier? i just can't find any definite view showing whats happening..

**Comment by shadowchemosh** [comment]
It sounds like a core HL bug actually.  When using the archetype to change ability score they maybe using the attribute score instead of the modifier. =(.

Was your Cha score 10?  What happens if you lower or raise your Cha score?

**Comment by shadowchemosh** [comment]
LW has replied that they have found this bug and it will be fixed in the next release of Pathfinder.

Closing this issue out!
