### ISSUE TITLE
[Ultimate Psionics] In-Progress Soulknife Archetypes and Favored Class Bonuses

### ISSUE THREAD

**Issue by Zaknaefin** [shadowchemosh/HL-Pack-Pathfinder#78]
The Armored Blade, Deadly Fist, Feral Heart, and Shielded Blade Soulknife Archetypes are all in the pack, but they are all in-progress with notes about not being fully implemented yet.  

Also, there are no alternate favored class bonuses for the core races for Soulknives and the psionic races just have the +1 power point option (beyond the standard 1 hp or 1 skill point).

**Comment by psych777** [comment]
it may have been better to split these two items into two separate 'issues'. 

for the archetypes, i'm a bit unclear. are you saying that the not fully implemented notes shouldn't be there? or are you complaining that because they are a work in progress that they haven't been completed yet? which is kind of the point of having the 'not fully implemented' messages, so people realize that something not functioning is because it hasn't been fully coded yet so they don't need to fill out a bug report....

**Comment by Zaknaefin** [comment]
The not fully implemented notes should be there, like you said, so people do not think its a bug as opposed to being a work in progress.  I just thought that in-progress items could be posted here in addition to the 'issues' (i.e. bugs).  My intent was not to complain.

**Comment by psych777** [comment]
ahh...i thought there was already an enhancement issue with those listed but just looked back through and there wasn't. 
at one point i was trying to at least get the text of the archetypes in so that they were selectable. some of the items requiring coding were beyond my knowledge at the time or just didn't have time to look closely at it. life has been too busy lately and now i feel like i've lost some of my herolab knowledge already haha.

**Comment by shadowchemosh** [comment]
Note to self still missing the following races FCB:  **~~Dwarf, Elf, Gnome, Half-Elf, Half-Orc & Halfling~~.**

Found on page 342.

**Comment by shadowchemosh** [comment]
All soulknife archetypes finished and all races FCB added. Closing issue.
