### ISSUE TITLE
Ultimate Psionics duplicates the Reptilian subtype

### ISSUE THREAD

**Issue by drumanagh** [shadowchemosh/HL-Pack-Pathfinder#82]
It looks like there's a reptilian subtype with tag `stReptilia` being supplied by one of the Wolf Lair supplements, but Ultimate Psionics is supplying a separate one with the tag `stReptile`.

**Comment by shadowchemosh** [comment]
Ok... I give.. What is the issue or bug?  If LW's version is coming from outside of the CORE license than I can't use it in this case.  The reason being that if a gamer only has the CORE license and I have bootstrapped LW's subtype than it will complain to them that they need to buy a Bestiary License.  That does not seem like a "good" plan for a person who just wants to use ONE PC Race out of UP. =)

If the issue is something else. Please list the specific issue and I can see about doing something to fix it.

Thanks

**Comment by drumanagh** [comment]
> Ok... I give.. What is the issue or bug?

There's at least one thing I know of, the Death Roll feat from Inner Sea Races, that's using the Reptilian subtype as a prereq. There's probably others scattered around that I haven't noticed yet.

> If LW's version is coming from outside of the CORE license than I can't use it in this case.

Would it be possible to duplicate the same tag without breaking things for people who do have the package that it's coming from?

**Comment by shadowchemosh** [comment]
Ah ok so the bug is that you found a feat that the UP race does not meet the Pre-Req of Reptilian Subtype.  That I can fix. =)
